services:

  server:
    build:
      context: .
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: package.json
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    networks:
      - custom-network

  db:
    image: postgres
    restart: always
    user: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=home-library
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - 5432:5432
    command:
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=logs"
      - "-c"
      - "log_statement=all"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - custom-network

volumes:
  db-data:

networks:
  custom-network:
    driver: bridge

secrets:
  db-password:
    file: db/password.txt
